customhost = "employee.c4efxykm2sat.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "linjingxuan-employee"
customregion = "us-east-1"
